download:
  year: 2023
  start_idx: 13240
  end_idx: 13250

prepare:
  path: "/home/clifford/clifford/clifflearns/insti/CS5830/a04/Downloaded_Data"

process:
  path: "/home/clifford/clifford/clifflearns/insti/CS5830/a04/Downloaded_Data"

evaluate:
  name_csv: "99999904237"